server:
  port: 8082

#spring:
#  main:
#    web-application-type: reactive
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          jwk-set-uri: ${auth-client-url}/realms/bmstu/protocol/openid-connect/certs
#      client:
#        provider:
#          keycloak:
#            issuer-uri: ${auth-client-url}/realms/bmstu
#            authorization-uri: ${auth-client-url}/realms/bmstu/protocol/openid-connect/auth
#            token-uri: ${auth-client-url}/realms/bmstu/protocol/openid-connect/token
#            user-info-uri: ${auth-client-url}/realms/bmstu/protocol/openid-connect/userinfo
#        registration:
#          keycloak:
#            client-id: bmstu
#            client-secret: 5fac7131-7bcc-41f6-bd2e-e78dfab18dfb
#
#services:
#  auth-client-url: http://192.168.0.13:8080/auth